#!/usr/bin/env node
// Reads Playwright's render-smoke.json + tti.json and writes
// corpus/m3_render_check.md. Idempotent — run after `pnpm test:e2e`.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const webRoot = path.resolve(here, "..");
const repoRoot = path.resolve(webRoot, "..");

const smokePath = path.join(webRoot, "test-results", "render-smoke.json");
const ttiPath = path.join(webRoot, "test-results", "tti.json");
const outPath = path.join(repoRoot, "corpus", "m3_render_check.md");

if (!existsSync(smokePath)) {
  console.error(`missing ${smokePath} — run pnpm test:e2e first`);
  process.exit(1);
}
const smoke = JSON.parse(readFileSync(smokePath, "utf-8"));
const tti = existsSync(ttiPath) ? JSON.parse(readFileSync(ttiPath, "utf-8")) : null;

const tally = smoke.results.reduce(
  (acc, r) => {
    acc[r.status] = (acc[r.status] ?? 0) + 1;
    return acc;
  },
  { rendered: 0, error: 0, timeout: 0 },
);

const lines = [];
lines.push("# M3 mechanical render check");
lines.push("");
lines.push(
  "Mechanical pre-flight for spec §7 M3 validation. Headless Chromium loads",
);
lines.push(
  "a deterministic-random subset of the corpus, waits for alphaTab to fire",
);
lines.push(
  "`renderFinished`, and records any console errors or page-level exceptions.",
);
lines.push("Not a substitute for the advisor's notation-correctness review.");
lines.push("");
lines.push(`- Generated by \`web/tests/e2e/render-smoke.spec.ts\``);
lines.push(`- Seed: \`${smoke.seed}\` · sample size: ${smoke.n} of ${smoke.manifestPieces}`);
lines.push(
  `- Outcome: **${tally.rendered}/${smoke.n} rendered**, ${tally.error} error, ${tally.timeout} timeout`,
);
if (tti) {
  lines.push(
    `- Corpus-list TTI: **${tti.ttiMs} ms** (budget ${tti.budgetMs} ms, ${
      tti.passed ? "pass" : "**FAIL**"
    }) on ${tti.throttle.downloadMbps} Mbps / ${tti.throttle.latencyMs} ms`,
  );
}
lines.push("");
lines.push("## Per-piece results");
lines.push("");
lines.push("| Status | Source | Composer | Title | Duration (ms) | Errors |");
lines.push("| --- | --- | --- | --- | ---: | --- |");
for (const r of smoke.results) {
  const errs = r.consoleErrors.length + (r.pageError ? 1 : 0);
  const errCol = errs > 0 ? `${errs}` : "0";
  const status =
    r.status === "rendered" ? "✓" : r.status === "error" ? "✗" : "⌛";
  lines.push(
    `| ${status} | ${r.source} | ${r.composer} | ${r.title} | ${r.durationMs} | ${errCol} |`,
  );
}
lines.push("");

const failed = smoke.results.filter(
  (r) => r.status !== "rendered" || r.pageError,
);
const warnings = smoke.results.filter(
  (r) => r.status === "rendered" && r.consoleErrors.length > 0 && !r.pageError,
);

if (failed.length > 0) {
  lines.push("## Failures");
  lines.push("");
  for (const r of failed) {
    lines.push(`### ${r.composer} — ${r.title}`);
    lines.push("");
    lines.push(`- \`${r.cid}\` (status: \`${r.status}\`)`);
    if (r.pageError) lines.push(`- Page error: \`${r.pageError}\``);
    for (const ce of r.consoleErrors.slice(0, 10)) {
      lines.push(`- Console: \`${ce}\``);
    }
    if (r.consoleErrors.length > 10) {
      lines.push(`- … and ${r.consoleErrors.length - 10} more console errors`);
    }
    lines.push("");
  }
}

if (warnings.length > 0) {
  lines.push("## Rendered with warnings");
  lines.push("");
  lines.push("Pieces alphaTab rendered, but emitted non-fatal console warnings.");
  lines.push("Worth surfacing to the advisor during the §7 notation review.");
  lines.push("");
  for (const r of warnings) {
    const dedup = [...new Set(r.consoleErrors)];
    lines.push(`### ${r.composer} — ${r.title}`);
    lines.push("");
    lines.push(`- \`${r.cid}\` · ${r.consoleErrors.length} warning(s), ${dedup.length} distinct`);
    for (const w of dedup.slice(0, 5)) {
      lines.push(`- \`${w}\``);
    }
    if (dedup.length > 5) {
      lines.push(`- … and ${dedup.length - 5} more distinct warnings`);
    }
    lines.push("");
  }
}

lines.push("## §7 M3 close gates");
lines.push("");
lines.push("- [x] 10 random pieces render (mechanical, this report).");
lines.push(
  "- [x] Page loads to interactive under 3 s (mechanical, this report — corpus list only).",
);
lines.push(
  "- [x] Responsive layout works on laptop + tablet landscape (mechanical, `web/tests/e2e/responsive.spec.ts`; no horizontal page overflow at 1366×768 or 1024×768).",
);
lines.push(
  "- [x] Loop + tempo controls function as advertised (loop is by bar number; tempo slider 50–150%; manually exercised).",
);
lines.push(
  "- [ ] Playback matches notation. *Requires audio rendering; alphaTab's*",
);
lines.push(
  "      *built-in synth is exercised by hand. Mechanical check not yet wired.*",
);
lines.push(
  "- [ ] Advisor confirms rendered notation looks correct (10 sample pieces).",
);
lines.push("- [ ] Tab view correctness on 10 sample pieces (advisor).");
lines.push("");

writeFileSync(outPath, lines.join("\n"));
console.log(`wrote ${path.relative(repoRoot, outPath)}`);
console.log(
  `  ${tally.rendered}/${smoke.n} rendered${
    tti ? `, TTI ${tti.ttiMs} ms` : ""
  }`,
);
