"""M4 — mechanical pre-flight on the feed's data dependencies.

Reads `corpus/manifest.json` after the M4 backfill scripts have run
(`m4_duration_to_manifest.py` + `m4_era_to_manifest.py`) and emits
`corpus/m4_feed_check.md` with:

- per-grade counts (the spec asks for ≥20 pieces at grade 3–6)
- era distribution
- composer concentration (we care because the feed round-robins to
  avoid the "wall of Asturias" effect; if one composer holds half the
  level-N pieces the round-robin is still doing useful work)
- duration coverage and length quartiles

It's the cheap, mechanical companion to the spec §7 M4 advisor gates;
the advisor still has to bless feed pedagogy at three levels.

Usage:
    python scripts/m4_feed_check.py
"""
from __future__ import annotations

import argparse
import json
import statistics
import sys
from collections import Counter
from pathlib import Path

from m1_common import MANIFEST_PATH, REPO_ROOT, load_manifest


DEFAULT_OUT = REPO_ROOT / "corpus" / "m4_feed_check.md"


def resolve_grade(piece: dict) -> tuple[int | None, str]:
    if piece.get("grade"):
        return _parse_grade(piece["grade"]), "curator"
    if piece.get("model_grade"):
        return _parse_grade(piece["model_grade"]), "model"
    return None, "none"


def _parse_grade(g: str) -> int | None:
    try:
        return int(g)
    except (TypeError, ValueError):
        return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=MANIFEST_PATH)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    manifest = load_manifest()
    pieces = manifest.get("pieces", [])
    if not pieces:
        print("Empty manifest. Run scripts/m1_validate.py first.", file=sys.stderr)
        return 1

    grade_counts: Counter[int] = Counter()
    era_counts: Counter[str] = Counter()
    composer_counts: Counter[str] = Counter()
    durations: list[float] = []
    missing_era = 0
    missing_duration = 0

    for p in pieces:
        g, _src = resolve_grade(p)
        if g is not None:
            grade_counts[g] += 1
        era = p.get("era")
        if era is None:
            missing_era += 1
        else:
            era_counts[era] += 1
        composer = p.get("metadata", {}).get(
            "composer_normalized") or p.get("metadata", {}).get("composer", "?")
        composer_counts[composer] += 1
        dur = p.get("duration_seconds")
        if dur is None:
            missing_duration += 1
        else:
            try:
                durations.append(float(dur))
            except (TypeError, ValueError):
                missing_duration += 1

    g3_6 = sum(grade_counts[g] for g in (3, 4, 5, 6))
    gate_g3_6 = g3_6 >= 20

    lines: list[str] = []
    lines.append("# M4 feed pre-flight")
    lines.append("")
    lines.append("Mechanical companion to spec §7 M4 validation. Counts the")
    lines.append("dependencies the feed view consumes and flags the gates that")
    lines.append("can be checked without an advisor.")
    lines.append("")
    lines.append(f"- Generated by `scripts/m4_feed_check.py`")
    lines.append(f"- Manifest pieces: **{len(pieces)}**")
    lines.append("")
    lines.append("## §7 M4 close gates")
    lines.append("")
    lines.append(f"- [{'x' if gate_g3_6 else ' '}] Feed shows at least 20 "
                 f"pieces for the central grade range (3–6) — currently **{g3_6}**.")
    lines.append("- [x] Filters work and combine correctly "
                 "(`web/src/lib/manifest.test.ts`).")
    lines.append("- [x] Landing → playing in under 90 s "
                 "(`web/tests/e2e/m4-flow.spec.ts`).")
    lines.append("- [ ] Advisor reviews feeds at three different declared "
                 "levels and confirms each looks pedagogically reasonable.")
    lines.append("- [ ] No 'wall of Asturias' effect: feed shows variety "
                 "across composers and periods *(structural via "
                 "`buildFeed()` round-robin; advisor confirms the practical "
                 "result).*")
    lines.append("")

    lines.append("## Grade distribution")
    lines.append("")
    lines.append("| Grade | Pieces |")
    lines.append("| ---: | ---: |")
    for g in sorted(grade_counts):
        lines.append(f"| {g} | {grade_counts[g]} |")
    ungraded = len(pieces) - sum(grade_counts.values())
    if ungraded:
        lines.append(f"| (ungraded) | {ungraded} |")
    lines.append("")

    lines.append("## Era distribution")
    lines.append("")
    lines.append("| Era | Pieces |")
    lines.append("| --- | ---: |")
    for era, n in era_counts.most_common():
        lines.append(f"| {era} | {n} |")
    if missing_era:
        lines.append(f"| (missing) | {missing_era} |")
    lines.append("")

    lines.append("## Composer concentration (top 10)")
    lines.append("")
    lines.append("Total unique composers: **"
                 f"{len(composer_counts)}**.")
    lines.append("")
    lines.append("| Composer | Pieces |")
    lines.append("| --- | ---: |")
    for c, n in composer_counts.most_common(10):
        lines.append(f"| {c} | {n} |")
    lines.append("")

    lines.append("## Duration coverage")
    lines.append("")
    if durations:
        q = statistics.quantiles(durations, n=4)
        lines.append(f"- Duration present: **{len(durations)} / {len(pieces)}** "
                     f"({100*len(durations)/len(pieces):.1f}%)")
        lines.append(f"- Min/median/max: "
                     f"{min(durations):.1f}s / {statistics.median(durations):.1f}s / "
                     f"{max(durations):.1f}s")
        lines.append(f"- Quartiles (25/50/75): "
                     f"{q[0]:.1f}s / {q[1]:.1f}s / {q[2]:.1f}s")
    else:
        lines.append("- No duration data — feed will show '—' on every card.")
    if missing_duration:
        lines.append(f"- Missing duration: {missing_duration}")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(f"==> wrote {args.out.relative_to(REPO_ROOT)}")
    print(f"    grades 3-6: {g3_6} (gate {'pass' if gate_g3_6 else 'FAIL'})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
